### ISSUE TITLE
Plugin extraction failed

### ISSUE THREAD

**Issue by Engholm** [shopwareLabs/SwagCustomNotification#1]
Hi,

I've just upgraded from SW 6.3.x to 6.4.1. After completition, I've tried to install the SwagCustomNotification for the first time. The installation failed with the following error message:

`Plugin extraction failed. Error: Destination directory "/www/shopware/custom/apps" is not writable`

The /custom/apps/ directory wasn't available. After creating the /apps directory manually, the installation extraction and installation worked fine.

I'm not sure if the separate /apps directory of the plugin is intentional?

Best regards
Björn

Shopware 6.4.1 CE / SwagCustomNotification 1.1.0

**Comment by keulinho** [comment]
Hi @Engholm,

thanks for raising this issue. 

Yes the seperate /apps dir is intentional and is required.

Can you give us a little bit more information of your shopware setup? What project-template do you use? The shopware/production or shopware/development repositories or a custom setup?

Kind regards
Jonas

**Comment by Engholm** [comment]
Hi @keulinho ,

This is the regular Shopware 6 Community Edition, which you could download from the homepage as a production version. Installed at the end of April 2020, from the beginning on PHP 7.4.x, MariaDB 10.3.x, Apache 2.4.
We use a child theme, but only with 2-3 minimal adjustments / overrides. 


Extensions that have been installed so far:
- Custom CSS/JS
- Custom Template (since 6.4.1)
- B2B - Only company registrations / Nur Firmenanmeldungen
- SwagCustomNotification (since 6.4.1)
- Shopware Store (since 6.4.1)

The SwagCustomNotification is the only plugin that needs this /custom/app directory. Everything else is in /custom/plugins.

So I was a bit puzzled.

best regards
Björn

**Comment by keulinho** [comment]
The SwagCustomNotification extension is build with the app-system and not the plugin-system, so the different installation path is expected, for more details on the app system please refer to our [docs](SwagCustomNotification).

We are currently investigating why the folder was missing, as that folder should be created out of the box.

**Comment by Engholm** [comment]
Thanks for clarifying!

**Comment by keulinho** [comment]
We found a problem where the app directory was not created automatically if you originally set up your shop on an older shopware version.
I've created a [ticket](https://issues.shopware.com/issues/NEXT-15704) for that and we will provide a fix in one of the upcoming shopware versions.

I'm closing this issue for now, as you can track the progress on the linked ticket, and in the meantime the workaround would be to create that folder manually.

Feel free to reopen the issue, if something is still missing.

Kind regards
Jonas
